apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "devsu-demo.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "devsu-demo.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
