apiVersion: v1
kind: Secret
metadata:
  name: {{ include "devsu-demo.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "devsu-demo.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secret }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
