apiVersion: v1
kind: Service
metadata:
  name: {{ include "devsu-demo.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "devsu-demo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "devsu-demo.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
